In [34]:
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_curve,roc_auc_score
import matplotlib.pyplot as plt
from sklearn.metrics import log_loss
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.model_selection import GridSearchCV
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder 
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.discriminant_analysis import 

In [2]:
import os
os.chdir(r'E:\PML\Datasets-20230112T094652Z-001\Datasets')
import pandas as pd

In [3]:
from sklearn.preprocessing import LabelEncoder
pix = pd.read_csv("Image Segmentation/Image_Segmention.csv")
pix.head(10)

Class  region.centroid.col  region.centroid.row  region.pixel.count  \
0  BRICKFACE                  188                  133                   9   
1  BRICKFACE                  105                  139                   9   
2  BRICKFACE                   34                  137                   9   
3  BRICKFACE                   39                  111                   9   
4  BRICKFACE                   16                  128                   9   
5  BRICKFACE                   26                   67                   9   
6  BRICKFACE                   14                  110                   9   
7  BRICKFACE                   11                  108                   9   
8  BRICKFACE                   85                  101                   9   
9  BRICKFACE                   18                  145                   9   

   short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0              0.000000                   0.0    0.333333  0.266667   
1              0.000000                   0.0    0.277778  0.107407   
2              0.000000                   0.0    0.500000  0.166667   
3              0.000000                   0.0    0.722222  0.374074   
4              0.000000                   0.0    0.500000  0.077778   
5              0.111111                   0.0    1.000000  0.888890   
6              0.000000                   0.0    1.722222  5.351851   
7              0.000000                   0.0    1.333333  0.800000   
8              0.000000                   0.0    1.333333  1.288888   
9              0.000000                   0.0    0.388889  0.018518   

   hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0    0.500000  0.077778        6.666666     8.333334      7.777778   
1    0.833333  0.522222        6.111111     7.555555      7.222222   
2    1.111111  0.474074        5.851852     7.777778      6.444445   
3    0.888889  0.429629        6.037037     7.000000      7.666666   
4    0.666667  0.311111        5.555555     6.888889      6.666666   
5    2.444445  3.185185       20.000000    19.555555     25.888890   
6    2.666667  1.022223       17.925926    18.888890     21.444445   
7    1.388889  0.951852       17.666666    19.000000     21.111110   
8    1.277778  1.218518       21.296297    21.222221     26.777779   
9    0.611111  0.374074        3.925926     5.555555      4.000000   

   rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0       3.888889    5.000000     3.333333     -8.333333    8.444445   
1       3.555556    4.333334     3.333333     -7.666666    7.555555   
2       3.333333    5.777778     1.777778     -7.555555    7.777778   
3       3.444444    2.888889     4.888889     -7.777778    7.888889   
4       3.111111    4.000000     3.333333     -7.333334    7.111111   
5      14.555555   -1.333333    17.666666    -16.333334   25.888890   
6      13.444445    2.888889    10.555555    -13.444445   21.444445   
7      12.888889    4.000000    10.333333    -14.333333   21.111110   
8      15.888889   -0.222222    16.444445    -16.222221   26.777779   
9       2.222222    4.888889     0.222222     -5.111111    5.555555   

   saturation.mean  hue-mean  
0         0.538580 -0.924817  
1         0.532628 -0.965946  
2         0.573633 -0.744272  
3         0.562919 -1.175773  
4         0.561508 -0.985811  
5         0.436939 -1.623202  
6         0.368848 -1.345096  
7         0.388756 -1.302133  
8         0.404792 -1.558599  
9         0.600529 -0.570940

In [7]:
x=pix.drop('Class',axis=1)
y=pix['Class']

In [14]:
label=LabelEncoder()
le_y=label.fit_transform(y)
le_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [16]:
kfold=StratifiedKFold(n_splits=5, shuffle=True, random_state=2023)
nb = GaussianNB()
res= cross_val_score(nb, x, le_y, scoring = 'neg_log_loss', cv=kfold)
print(res)
print(res.mean())



[-5.69429675 -1.71003266 -5.00025803 -2.47940234 -4.69608346]
-3.916014650972882


In [ ]:
# IMAGE SEGMENTATION

In [17]:
pix = pd.read_csv("Image Segmentation/Image_Segmention.csv")
pix.head(10)

Class  region.centroid.col  region.centroid.row  region.pixel.count  \
0  BRICKFACE                  188                  133                   9   
1  BRICKFACE                  105                  139                   9   
2  BRICKFACE                   34                  137                   9   
3  BRICKFACE                   39                  111                   9   
4  BRICKFACE                   16                  128                   9   
5  BRICKFACE                   26                   67                   9   
6  BRICKFACE                   14                  110                   9   
7  BRICKFACE                   11                  108                   9   
8  BRICKFACE                   85                  101                   9   
9  BRICKFACE                   18                  145                   9   

   short.line.density.5  short.line.density.2  vedge.mean  vegde.sd  \
0              0.000000                   0.0    0.333333  0.266667   
1              0.000000                   0.0    0.277778  0.107407   
2              0.000000                   0.0    0.500000  0.166667   
3              0.000000                   0.0    0.722222  0.374074   
4              0.000000                   0.0    0.500000  0.077778   
5              0.111111                   0.0    1.000000  0.888890   
6              0.000000                   0.0    1.722222  5.351851   
7              0.000000                   0.0    1.333333  0.800000   
8              0.000000                   0.0    1.333333  1.288888   
9              0.000000                   0.0    0.388889  0.018518   

   hedge.mean  hedge.sd  intensity.mean  rawred.mean  rawblue.mean  \
0    0.500000  0.077778        6.666666     8.333334      7.777778   
1    0.833333  0.522222        6.111111     7.555555      7.222222   
2    1.111111  0.474074        5.851852     7.777778      6.444445   
3    0.888889  0.429629        6.037037     7.000000      7.666666   
4    0.666667  0.311111        5.555555     6.888889      6.666666   
5    2.444445  3.185185       20.000000    19.555555     25.888890   
6    2.666667  1.022223       17.925926    18.888890     21.444445   
7    1.388889  0.951852       17.666666    19.000000     21.111110   
8    1.277778  1.218518       21.296297    21.222221     26.777779   
9    0.611111  0.374074        3.925926     5.555555      4.000000   

   rawgreen.mean  exred.mean  exblue.mean  exgreen.mean  value.mean  \
0       3.888889    5.000000     3.333333     -8.333333    8.444445   
1       3.555556    4.333334     3.333333     -7.666666    7.555555   
2       3.333333    5.777778     1.777778     -7.555555    7.777778   
3       3.444444    2.888889     4.888889     -7.777778    7.888889   
4       3.111111    4.000000     3.333333     -7.333334    7.111111   
5      14.555555   -1.333333    17.666666    -16.333334   25.888890   
6      13.444445    2.888889    10.555555    -13.444445   21.444445   
7      12.888889    4.000000    10.333333    -14.333333   21.111110   
8      15.888889   -0.222222    16.444445    -16.222221   26.777779   
9       2.222222    4.888889     0.222222     -5.111111    5.555555   

   saturation.mean  hue-mean  
0         0.538580 -0.924817  
1         0.532628 -0.965946  
2         0.573633 -0.744272  
3         0.562919 -1.175773  
4         0.561508 -0.985811  
5         0.436939 -1.623202  
6         0.368848 -1.345096  
7         0.388756 -1.302133  
8         0.404792 -1.558599  
9         0.600529 -0.570940

In [20]:
X=pix.drop("Class",axis=1)
Y=pix['Class']
y

0      BRICKFACE
1      BRICKFACE
2      BRICKFACE
3      BRICKFACE
4      BRICKFACE
         ...    
204        GRASS
205        GRASS
206        GRASS
207        GRASS
208        GRASS
Name: Class, Length: 209, dtype: object

In [28]:
label=LabelEncoder()
le_y=label.fit_transform(y)
le_y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [32]:
kfold=StratifiedKFold(n_splits=5,shuffle=True ,random_state=2023)
lda=LinearDiscriminantAnalysis()

NameError: name 'LinearDiscriminantAnalysis' is not defined